name: RetinaLogos
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - cudatoolkit=11.8.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjitlink=12.1.105
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - pillow=11.0.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.11.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - av==14.0.1
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - blessed==1.20.0
      - boto3==1.35.98
      - botocore==1.35.98
      - cffi==1.17.1
      - click==8.1.8
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.3.2
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.32.2
      - dill==0.3.8
      - docopt==0.6.2
      - einops==0.8.0
      - environs==14.1.0
      - executing==2.1.0
      - fairscale==0.4.13
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - flash-attn==2.7.2.post1
      - fonttools==4.55.8
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gpustat==1.1.1
      - gradio==5.11.0
      - gradio-client==1.5.3
      - grpcio==1.69.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - humanfriendly==10.0
      - humanize==4.11.0
      - importlib-metadata==8.5.0
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.12.3
      - isoduration==20.11.0
      - jedi==0.19.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.25.1
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.1
      - multidict==6.1.0
      - multiprocess==0.70.16
      - multiprocessing-logging==0.3.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - nvidia-ml-py==12.560.30
      - nvitop==1.4.2
      - orjson==3.10.14
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.15.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==3.2.1
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyzmq==26.2.1
      - qwen-vl-utils==0.0.8
      - referencing==0.36.2
      - regex==2024.11.6
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruff==0.9.0
      - s3transfer==0.10.4
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tomlkit==0.13.2
      - torchdiffeq==0.2.5
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.47.1
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2024.2
      - uri-template==1.3.0
      - uvicorn==0.34.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==14.1
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarg==0.1.9
      - yarl==1.18.3
      - zipp==3.21.0
